### ISSUE TITLE
Argument of type 'QueueingSubject<{}>' is not assignable to parameter of type 'Observable<any>'

### ISSUE THREAD

**Issue by mikebridge** [ohjames/rxjs-websockets#13]
With rxjs-websockets 1.1.0, queueing-subject 0.1.1 & typescript 2.4.2 I have the following code:

```typescript
import Rx from "rxjs/Rx";
import { QueueingSubject } from "queueing-subject";
import websocketConnect, {Connection} from "rxjs-websockets";

const queuingSubject = new QueueingSubject();

// ...

const connection: Connection =  websocketConnect(
    myUrl,
    queuingSubject,
    myWebSocket
);
```

After upgrading from rxjs 5.4.2 to 5.4.3 I get the following type error in the webSocketConnect call:

```
error TS2345: Argument of type 'QueueingSubject<{}>' is not assignable to parameter of type 'Observable<any>'.  
Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.
```

I cleaned the cache (I'm using yarn), deleted node_modules and reinstalled but still get this error....

**Comment by ohjames** [comment]
You need to add a type parameter to the queueing subject.

**Comment by mikebridge** [comment]
@ohjames I experimented with various types, e.g. `QueueingSubject<any>()` but couldn't get rid of the error.  However, both `QueuingSubject` and `QueueingSubject<any>` are working with Typescript 2.5.0.

**Comment by ohjames** [comment]
it works fine for me with ts 2.4.2 and <any> on the subject.

**Comment by mikebridge** [comment]
@ohjames is that with yarn or npm?

**Comment by ohjames** [comment]
Why would that make a difference?

**Comment by mikebridge** [comment]
Because this isn't the only problem I had, and several others seem related to either having multiple versions of something after upgrade, or else transitive dependency resolution confusion.

**Comment by ohjames** [comment]
*suspicious face*

**Comment by danielcrisp** [comment]
@mikebridge @ohjames 

I'm having a pretty similar problem - did you ever get this sorted?

![image](https://user-images.githubusercontent.com/1104814/31400151-7dc693a0-ade6-11e7-9d26-c9360c995e90.png)

<img width="614" alt="screen shot 2017-10-10 at 18 13 14" src="https://user-images.githubusercontent.com/1104814/31400238-c47aaa52-ade6-11e7-9497-9f3d73caa220.png">

Shouldn't this line also allow for the `QueueingSubject` type?

https://github.com/ohjames/rxjs-websockets/blob/master/src/index.ts#L25

**Comment by mikebridge** [comment]
@ohjames  I never figured out whether it was a yarn issue or an issue with the packages themselves, but removing everything in `node_modules` and re-installing fixed it for me.

**Comment by danielcrisp** [comment]
Hmm no joy for me. I've tried a fresh `node_modules` install with both `npm` and yarn`.

Even using _as_ it doesn't like it:

![image](https://user-images.githubusercontent.com/1104814/31403188-5456d264-adf0-11e7-888f-90e1cc25cc3a.png)

It's pretty weird because even if I use a real `Observable<string>` it still complains!

**Comment by danielcrisp** [comment]
Ok, I'm using this workaround: https://stackoverflow.com/a/41661734 (the cache clean approach didn't work)

But now I'm seeing strange errors like `Property 'share' does not exist on type Observable<string>` when I try to share the `messages` observable. Although it builds ok.

Something is definitely up with this package!

**Comment by ohjames** [comment]
@danielcrisp Something isn't up with the package, that's a rudimentary error with rxjs module system that has been falsely reported by two other people already now. You need to:

`import 'rxjs/add/operator/share` to get `share()`.

As for the previous issue, this is because you have two copies of rxjs (and thus two different `Observable` types). Again a packaging error unrelated to `rxjs-websockets`. Make sure that all of your `rxjs` dependencies are of an exact identical version so that they can be deduplicated into a single package.

**Comment by ohjames** [comment]
For the lacking `share()` operator check out the rxjs docs: https://github.com/Reactive-Extensions/RxJS/tree/master/src/modular (ctrl+F for "Batteries Included").

For the previous issue, you need to understand npm better.

**Comment by ohjames** [comment]
I'm starting to suspect I need to make `rxjs` a peer and dev dependency... I've gotten really bad advice on peer dependencies in the past from people which it looks like I shouldn't have trusted.

**Comment by ohjames** [comment]
Relying on npm dependency duplication as I had advised isn't a good idea at all... in a previous package I was told by someone I was handling dependencies wrong and they misinformed me and I never bothered to verify. I've taken the time to understand peer dependencies fully now and can see it is the right choice for this project.

Released version 4.0.0 with the fix, sorry for the confusion!

**Comment by danielcrisp** [comment]
Great! Thanks James
